name: X Content Automation

on:
  schedule:
    - cron: "5 * * * *"  # يعمل كل ساعة عند الدقيقة 05 (بتوقيت UTC)
  workflow_dispatch:      # تشغيل يدوي من Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run RSS → Notion
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
        run: |
          python src/rss_to_notion.py
      - name: Generate Tweets
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
        run: |
          python src/generate_tweets.py --limit 5
      - name: Notify Telegram (optional)
        if: secrets.TELEGRAM_BOT_TOKEN != '' && secrets.TELEGRAM_CHAT_ID != ''
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python src/notify_telegram.py
      # - name: Post to X (optional – requires X API access)
      #   env:
      #     NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
      #     NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
      #     X_API_KEY: ${{ secrets.X_API_KEY }}
      #     X_API_SECRET: ${{ secrets.X_API_SECRET }}
      #     X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
      #     X_ACCESS_SECRET: ${{ secrets.X_ACCESS_SECRET }}
      #   run: |
      #     pip install tweepy
      #     python src/post_to_x.py
